apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
  annotations:
    # needed on gke
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  commonName: "tensorbeat.com"
  dnsNames:
    - "tensorbeat.com"
    - "kubeapps.tensorbeat.com"
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer