apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: istio-system
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mrthinger@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: istio