apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: redis
  name: redis-service
spec:
  hosts:
  - "redis.tensorbeat.com"
  gateways:
  - default/tensorbeat-gateway
  tcp:
    - route:
      - destination:
          host: redis-master.redis.svc.cluster.local
          port:
            number: 6379